export const Success = "success";
export const Warning = "warning";
export const Info = "info";
export const Err = "error";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const SELECTED_DATAFLOW = "SELECTED_DATAFLOW";
export const DASHBOARD_DATA = "DASHBOARD_DATA";
export const DASHBOARD_FETCH_SUCCESS = "DASHBOARD_FETCH_SUCCESS";
export const DASHBOARD_FETCH_FAILUR = "DASHBOARD_FETCH_FAILUR";

export const DASHBOARD_STUDIES = "DASHBOARD_STUDIES";
export const FETCH_DASHBOARD_STUDY_SUCCESS = "FETCH_DASHBOARD_STUDY_SUCCESS";
export const FETCH_DASHBOARD_STUDY_FAILUR = "FETCH_DASHBOARD_STUDY_FAILUR";

export const PAGEHEADER_UPDATE = "PAGEHEADER_UPDATE";
export const UPDATE_DS = "UPDATE_DS";
export const RESET_FTP_FORM = "RESET_FTP_FORM";
export const RESET_JDBC_FORM = "RESET_JDBC_FORM";

export const GET_DATA_FLOW_LIST = "GET_DATA_FLOW_LIST";
export const GET_DATA_FLOW_LIST_SUCCESS = "GET_DATA_FLOW_LIST_SUCCESS";
export const GET_DATA_FLOW_LIST_FAILURE = "GET_DATA_FLOW_LIST_FAILURE";

export const GET_STUDIES_LIST = "GET_STUDIES_LIST";
export const GET_STUDIES_LIST_SUCCESS = "GET_STUDIES_LIST_SUCCESS";
export const GET_STUDIES_LIST_FAILURE = "GET_STUDIES_LIST_FAILURE";

export const GET_PINNED_LIST = "GET_PINNED_LIST";
export const GET_PINNED_LIST_SUCCESS = "GET_PINNED_LIST_SUCCESS";
export const GET_PINNED_LIST_FAILURE = "GET_PINNED_LIST_FAILURE";

export const ADD_DATAFLOW = "ADD_DATAFLOW";
export const ADD_DATAFLOW_SUCCESS = "ADD_DATAFLOW_SUCCESS";
export const ADD_DATAFLOW_FAILURE = "ADD_DATAFLOW_FAILURE";

export const DATAFLOWS_LIST_FAILURE = "DATAFLOWS_LIST_FAILURE";
export const UPDATE_HEADER_COUNT = "UPDATE_HEADER_COUNT";
export const UPDATE_DF_STATUS = "UPDATE_DF_STATUS";

export const PACKAGES_LIST = "PACKAGES_LIST";
export const ADD_PACKAGE_BTN = "ADD_PACKAGE_BTN";
export const PACKAGES_LIST_SUCCESS = "PACKAGES_LIST_SUCCESS";
export const PACKAGES_LIST_FAILURE = "PACKAGES_LIST_FAILURE";

export const ADD_DATA_PACKAGE = "ADD_DATA_PACKAGE";
export const ADD_PACKAGE_SUCCESS = "ADD_PACKAGE_SUCCESS";
export const ADD_PACKAGE_FAILURE = "ADD_PACKAGE_FAILURE";
export const EDIT_DATA_PACKAGE = "EDIT_DATA_PACKAGE";

export const UPDATE_DATA_PACKAGE = "UPDATE_DATA_PACKAGE";
export const UPDATE_DATA_PACKAGE_SUCCESS = "UPDATE_DATA_PACKAGE_SUCCESS";
export const UPDATE_DATA_PACKAGE_FAILURE = "UPDATE_DATA_PACKAGE_FAILURE";

export const GET_LOCATIONS_DATA = "GET_LOCATIONS_DATA";
export const UPDATE_LEFT_PANEL = "UPDATE_LEFT_PANEL";
export const UPDATE_DS_STATUS = "UPDATE_DS_STATUS";

export const GET_DATA_KIND = "GET_DATA_KIND";
export const FETCH_DATAKIND_SUCCESS = "FETCH_DATAKIND_SUCCESS";
export const FETCH_DATAKIND_FAILURE = "FETCH_DATAKIND_FAILURE";

export const GET_LOCATIONS_ADMIN = "GET_LOCATIONS_ADMIN";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_FAILURE = "FETCH_LOCATION_FAILURE";

export const GET_LOCATION_DETAIL = "GET_LOCATION_DETAIL";
export const FETCH_LOCATION_DETAIL_SUCCESS = "FETCH_LOCATION_DETAIL_SUCCESS";
export const FETCH_LOCATION_DETAIL_FAILURE = "FETCH_LOCATION_DETAIL_FAILURE";

export const PREVENT_CD_VERSION_BUMP = "PREVENT_CD_VERSION_BUMP";

export const GET_VENDORS_DATA = "GET_VENDORS_DATA";
export const FETCH_VENDOR_SUCCESS = "FETCH_VENDOR_SUCCESS";
export const FETCH_VENDOR_FAILURE = "FETCH_VENDOR_FAILURE";

export const UPDATE_SELECTED_LOCATION = "UPDATE_SELECTED_LOCATION";
export const UPDATE_FORM_FIELDS = "UPDATE_FORM_FIELDS";
export const SAVE_LOCATION_DATA = "SAVE_LOCATION_DATA";
export const UPDATE_LOCATION_DATA = "UPDATE_LOCATION_DATA";
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_FAILURE = "UPDATE_LOCATION_FAILURE";

export const GET_SERVICE_OWNERS = "GET_SERVICE_OWNERS";
export const FETCH_SERVICE_OWNERS_SUCCESS = "FETCH_SERVICE_OWNERS_SUCCESS";
export const FETCH_SERVICE_OWNERS_FAILURE = "FETCH_SERVICE_OWNERS_FAILURE";

export const GET_PASSWORD_LOCATION = "GET_PASSWORD_LOCATION";
export const FETCH_LOCATION_PASSWORD_SUCCESS =
  "FETCH_LOCATION_PASSWORD_SUCCESS";
export const FETCH_LOCATION_PASSWORD_FAILURE =
  "FETCH_LOCATION_PASSWORD_FAILURE";

export const GET_DATAFLOW_DETAIL = "GET_DATAFLOW_DETAIL";
export const RESET_DF_FORMDATA = "RESET_DF_FORMDATA";
export const FETCH_DATAFLOW_DETAIL_SUCCESS = "FETCH_DATAFLOW_DETAIL_SUCCESS";
export const FETCH_DATAFLOW_DETAIL_FAILURE = "FETCH_DATAFLOW_DETAIL_FAILURE";
export const FETCH_DATAFLOW_LOCAL_DETAIL = "FETCH_DATAFLOW_LOCAL_DETAIL";
export const SAVE_DATAFLOW_LOCAL_DETAIL = "SAVE_DATAFLOW_LOCAL_DETAIL";

export const GET_DATASET_DETAIL = "GET_DATASET_DETAIL";
export const FETCH_DATASET_DETAIL_SUCCESS = "FETCH_DATASET_DETAIL_SUCCESS";
export const FETCH_DATASET_DETAIL_FAILURE = "FETCH_DATASET_DETAIL_FAILURE";

export const GET_LOCATION_BY_TYPE = "FETCH_SERVICE_OWNERS_FAILURE";
export const STORE_LOCATION_SUCCESS = "STORE_LOCATION_SUCCESS";
export const STORE_LOCATION_FAILURE = "STORE_LOCATION_FAILURE";

export const HIDE_ERROR_MSG = "HIDE_ERROR_MSG";

export const AUDIT_LOGS = "AUDIT_LOGS";
export const AUDIT_LOGS_SUCCESS = "AUDIT_LOGS_SUCCESS";
export const AUDIT_LOGS_FAILURE = "AUDIT_LOGS_FAILURE";

export const REDIRECT_TO_DATASET = "REDIRECT_TO_DATASET";
export const SAVE_DATASET_DATA = "SAVE_DATASET_DATA";
export const UPDATE_DATASET_DATA = "UPDATE_DATASET_DATA";
export const STORE_DATASET_SUCCESS = "STORE_DATASET_SUCCESS";
export const STORE_DATASET_FAILURE = "STORE_DATASET_FAILURE";

export const SAVE_DATASET_COLUMNS = "SAVE_DATASET_COLUMNS";
export const STORE_DATASET_COLUMNS_SUCCESS = "STORE_DATASET_COLUMNS_SUCCESS";
export const STORE_DATASET_COLUMNS_FAILURE = "STORE_DATASET_COLUMNS_FAILURE";

export const UPDATE_DATASET_SUCCESS = "UPDATE_DATASET_SUCCESS";
export const UPDATE_DATASET_FAILURE = "UPDATE_DATASET_FAILURE";

export const UPDATE_COLUMNS_DATA = "UPDATE_COLUMNS_DATA";
export const UPDATE_COLUMNS_SUCCESS = "UPDATE_COLUMNS_SUCCESS";
export const UPDATE_COLUMNS_FAILURE = "UPDATE_COLUMNS_FAILURE";

export const GET_DATASET_COLUMNS = "GET_DATASET_COLUMNS";
export const FETCH_DATASET_COLUMNS_SUCCESS = "FETCH_DATASET_COLUMNS_SUCCESS";
export const FETCH_DATASET_COLUMNS_FAILURE = "FETCH_DATASET_COLUMNS_FAILURE";

export const GET_VLC_RULES = "GET_VLC_RULES";
export const FETCH_VLC_RULES_SUCCESS = "FETCH_VLC_RULES_SUCCESS";
export const FETCH_VLC_RULES_FAILURE = "FETCH_VLC_RULES_FAILURE";

export const GET_CDT_LIST = "GET_CDT_LIST";
export const FETCH_CDT_LIST_SUCCESS = "FETCH_CDT_LIST_SUCCESS";
export const FETCH_CDT_LIST_FAILURE = "FETCH_CDT_LIST_FAILURE";

export const GET_SQL_TABLES = "GET_SQL_TABLES";
export const FETCH_SQL_TABLES_SUCCESS = "FETCH_SQL_TABLES_SUCCESS";
export const FETCH_SQL_TABLES_FAILURE = "FETCH_SQL_TABLES_FAILURE";

export const GET_SQL_COLUMNS = "GET_SQL_COLUMNS";
export const FETCH_SQL_COLUMNS_SUCCESS = "FETCH_SQL_COLUMNS_SUCCESS";
export const FETCH_SQL_COLUMNS_FAILURE = "FETCH_SQL_COLUMNS_FAILURE";

export const GET_PREVIEW_SQL = "GET_PREVIEW_SQL";
export const FETCH_PREVIEW_SQL_SUCCESS = "FETCH_PREVIEW_SQL_SUCCESS";
export const FETCH_PREVIEW_SQL_FAILURE = "FETCH_PREVIEW_SQL_FAILURE";

export const GET_DATASET_INGESTION_SUMMARY = "GET_DATASET_INGESTION_SUMMARY";
export const GET_DATASET_INGESTION_SUMMARY_SUCCESS =
  "GET_DATASET_INGESTION_SUMMARY_SUCCESS";
export const GET_DATASET_INGESTION_SUMMARY_FAILURE =
  "GET_DATASET_INGESTION_SUMMARY_FAILURE";

export const FETCH_SETTINGS_DATA = "FETCH_SETTINGS_DATA";
export const CREARE_SETTINGS_DATA = "CREARE_SETTINGS_DATA";
export const UPDATE_SETTINGS_DATA = "UPDATE_SETTINGS_DATA";
export const SEARCH_SETTINGS_DATA = "SEARCH_SETTINGS_DATA";

export const FETCH_SETTINGS_SUCCESS = "FETCH_SETTINGS_SUCCESS";
export const FETCH_SETTINGS_FAILURE = "FETCH_SETTINGS_FAILURE";
export const CREARE_SETTINGS_SUCCESS = "CREARE_SETTINGS_SUCCESS";
export const CREARE_SETTINGS_FAILURE = "CREARE_SETTINGS_FAILURE";
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS";
export const UPDATE_SETTINGS_FAILURE = "UPDATE_SETTINGS_FAILURE";

export const GET_TRANSFER_LOG = "GET_TRANSFER_LOG";
export const FETCH_TRANSFER_LOG_SUCCESS = "FETCH_TRANSFER_LOG_SUCCESS";
export const FETCH_TRANSFER_LOG_FAILURE = "FETCH_TRANSFER_LOG_FAILURE";

export const GET_DATASET_PROPERTIES = "GET_DATASET_PROPERTIES";
export const FETCH_DATASET_PROPERTIES_SUCCESS =
  "FETCH_DATASET_PROPERTIES_SUCCESS";
export const FETCH_DATASET_PROPERTIES_FAILURE =
  "FETCH_DATASET_PROPERTIES_FAILURE";

export const GET_DATASET_INGESTION_ISSUE_TYPES =
  "GET_DATASET_INGESTION_ISSUE_TYPES";
export const FETCH_DATASET_INGESTION_ISSUE_TYPES_SUCCESS =
  "FETCH_DATASET_INGESTION_ISSUE_TYPES_SUCCESS";
export const FETCH_DATASET_INGESTION_ISSUE_TYPES_FAILURE =
  "FETCH_DATASET_INGESTION_ISSUE_TYPES_FAILURE";

export const GET_DATASET_INGESTION_FILE_HISTORY =
  "GET_DATASET_INGESTION_FILE_HISTORY";
export const FETCH_DATASET_INGESTION_FILE_HISTORY_SUCCESS =
  "FETCH_DATASET_INGESTION_FILE_HISTORY_SUCCESS";
export const FETCH_DATASET_INGESTION_FILE_HISTORY_FAILURE =
  "FETCH_DATASET_INGESTION_FILE_HISTORY_FAILURE";
// API URLS

export const GETSTUDYDF = "v1/api/dataflow/studyDataflowList";
export const STUDYSEARCH = "v1/api/study/search-study";
export const STUDYAPI = "v1/api/study";
export const HARDDELETE = "v1/api/dataflow/hard-delete";
export const SYNCNOW = "v1/api/dataflow/syncNow";
export const ACTIVATEDF = "v1/api/dataflow/activate";
export const INACTIVATE = "v1/api/dataflow/inActivate";
export const DATAFLOW_SAVE = "v1/api/dataflow/create";
export const DATAFLOW_UPDATE_API = "v1/api/dataflow/update-config";
export const DATAFLOWSEARCH = "v1/api/dataflow/search-dataflow";
export const DATAFLOW_SOURCE = "v1/api/dataflow";
export const DATAFLOW_DETAILS = "v1/api/dataflow/details";
export const TOGGLE_DF_BTN = "TOGGLE_DF_BTN";

export const PACKAGES_SEARCH = "v1/api/data-package/search";
export const ADD_PACKAGE = "v1/api/data-package/add";
export const DELETE_PACKAGE = "v1/api/data-package/delete";
export const UPDATE_PACKAGE = "v1/api/data-package/update-status";
export const NOT_ONBOARDED_FETCH = "v1/api/study/notonboarded-studies-stat";
export const STUDYLIST = "v1/api/study/listbyUser";
export const PINNEDSTUDY = "v1/api/study/pinnedStudies";
export const UNPINSTUDY = "v1/api/study/unPinStudy";
export const PINSTUDY = "v1/api/study/pinStudy";
export const AUDIT_LOGS_FETCH = "v1/api/audit-logs/get";

export const LOCATIONAPI = "v1/api/location";
export const LOCATIONPASSWORDAPI = "v1/api/location/get_password";

export const VENDORAPI = "v1/api/vendor";
export const DATAKINDAPI = "v1/api/datakind";
export const DATASETAPI = "v1/api/dataset";
export const COLUMNSAPI = "v1/api/columnset";
export const DATAFLOWAPI = "v1/api/dataflow";
export const VLCDATAAPI = "v1/api/dataset/getVLCData";
export const SQLTABLESAPI = "v1/api/dataset/getTables";
export const SQLCOLUMNSAPI = "v1/api/dataset/getColumns";
export const PREVIEWSQLAPI = "v1/api/dataset/previewSQL";
export const SETTINGAPI = "v1/api/system-settings";
export const INGESTIONREPORTAPI = "v1/api/dataset/ingestion-report";

export const baseURL = process.env.REACT_APP_API_URL;

export const allowedTypes = [
  "xlsx",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "csv",
];

export const hive2CDP = "com.cloudera.hive.jdbc41.HS2Driver";
export const hive2CDH = "com.cloudera.hive.jdbc41.HS2Driver";
export const oracle = "oracle.jdbc.driver.OracleDriver";
export const SQLServer = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
export const impala = "com.cloudera.impala.jdbc41.Driver";
export const PostgreSQL = "org.postgresql.Driver";
export const locationExistInDFMsg =
  "IP Server or DB Hostname cannot be inactivated until removed from all data flows using this location.";
